[project]
name = 'Decentralized-Veterinary-Pharmaceutical-Distribution'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.distributor-verification]
path = 'contracts/distributor-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.drug-tracking]
path = 'contracts/drug-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
